import turtle

window = turtle.Screen()
turtle.reset()

turtle.shape("circle")
turtle.bgcolor("white")
turtle.color("black")
turtle.speed(5)
turtle.pensize(5)

turtle.penup()
turtle.goto(200, 0)
turtle.left(90)
turtle.pendown()
turtle.circle(200)
turtle.penup()
turtle.goto(200, 0)
turtle.pendown()
turtle.left(45)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.left(90)
turtle.circle(-200, 45)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()


for i in range(4):
	turtle.forward(200)
	turtle.penup()
	turtle.goto(0, 0)
	turtle.pendown()
	turtle.left(45)
	turtle.forward(200)
	turtle.penup()
	turtle.goto(0, 0)
	turtle.pendown()
	turtle.left(45)

window.exitonclick()
