# Задание 1
import turtle
window = turtle.Screen()
turtle.reset()
# Step 1
turtle.shape("turtle")
turtle.bgcolor("red")
turtle.color("blue")
# Step 2
turtle.speed(5)
turtle.pensize(3)
# Step 3
turtle.penup()
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.pendown()

turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)


#Задание 2
# Квадрат
turtle.shape("circle")
turtle.bgcolor("blue")
turtle.color("orange")
turtle.speed(1)
turtle.pensize(6)
turtle.penup()
turtle.left(30)
turtle.forward(300)
turtle.left(90)
turtle.pendown()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
# Треугольник
turtle.shape("square")
turtle.bgcolor("white")
turtle.color("orange")
turtle.speed(1)
turtle.pensize(4)
turtle.penup()
turtle.left(180)
turtle.forward(105)
turtle.right(90)
turtle.pendown()
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(100)
# Круг
turtle.shape("triangle")
turtle.color("pink")
turtle.speed(1)
turtle.pensize(3)
turtle.penup()
turtle.left(180)
turtle.forward(100)
turtle.left(30)
turtle.forward(5)
turtle.pendown()
turtle.right(90)
turtle.circle(100)
window.exitonclick()
